---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - authproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - authproviders/finalizers
  verbs:
  - update
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - authproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - support.argoproj.extensions.io
  resources:
  - supports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - support.argoproj.extensions.io
  resources:
  - supports/finalizers
  verbs:
  - update
- apiGroups:
  - support.argoproj.extensions.io
  resources:
  - supports/status
  verbs:
  - get
  - patch
  - update
